### ISSUE TITLE
Suggestion: Attachments

### ISSUE THREAD

**Issue by Tikkle** [MagmaGuy/BetterStructures#17]
Hey MagmaGuy,

I'm very much enjoying the plugin and so are my players. Thank you so much for the hard work and hours you've put into making this plugin viable for production servers.

I'd like to suggest a new feature for your consideration. Adding a new `schem.yml` config option called `Attachments:`- with a corresponding Special Block. For purposes of demonstration, the Special Block material will be a `JIGSAW`. Here is an example of the `schem.yml` config, the explanation and functionality are below it:

```YAML
isEnabled: true
weight: 1.0
pedestalMaterial: optional
generatorConfigFilename: generator.yml
Attachments:
  isEnabled: true/false
  numberToAttach: 1-10 # range of attachments, number is randomly selected by plugin when generating structure.
  attachmentSchems:
    attachment_custom_name:
      isEnabled: true/false
      fileName: 'attachment_one.schem'
      canHaveChildren: true/false # defaults to False if unspecified.
      numberOfChildren: 0-10 # range of children, number is randomly selected by plugin when generating structure. Dependant on 'canHaveChildren: true'
      childrenSchems:
        child_custom_name:
          isEnabled: true/false
          fileName: 'child_of_attachment_one.schem'
        child_two_custom_name:
          isEnabled: true/false
          fileName: 'child_of_attachment_one.schem'
    attachment__two_custom_name:
      isEnabled: true/false
      fileName: 'attachment_two.schem'
```

This feature's functionality would be the same as how Datapacks use Structure and Jigsaw blocks to put together structures (e.g. Strongholds, Mineshafts, etc).

Users would place a `JIGSAW` on the edge of their schematics with the "arrow" of the Jigsaw block pointing in the direction of the attachment:

![2023-03-30_12 36 06](https://user-images.githubusercontent.com/14956067/228908745-8c314f2b-de7f-4901-884d-2ad94d28babb.png)

**This is how it would look when the schem has an attachment:**

![2023-03-30_12 38 21](https://user-images.githubusercontent.com/14956067/228908755-1a8270fa-1c79-4d08-9227-0f6971121d3a.png)
![2023-03-30_12 40 15](https://user-images.githubusercontent.com/14956067/228908756-c66bfa3e-6381-45d6-bf0f-ca6400de5e58.png)

The way the "arrow" on the `JIGSAW` is facing would tell the plugin where to generate the attachments and their children (up, down, right, left, north, south, etc).

Attachments could also have "Children" (attachment of the Attachment) that operate in the same way as the Attachment to Main.shem.

Pardon my ignorance if there is already a way to achieve this in your plugin as I have only been utilizing BetterStructures for the better part of 2 weeks.

I'd love to have this feature and would be willing to send you some lunch money to get it added 😉

Sincerely,
Tikkle
